language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio run

before_deploy:
  - find .pioenvs -name "firmware.elf" | xargs -n1 dirname | xargs -n1 basename | xargs -n1 -I{} mv .pioenvs/{}/firmware.elf ./{}.bin

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH
  file_glob: true
  file: "*.bin"
  skip_cleanup: true
  on:
    tags: true
